spring.application.name=interdisciplinar
server.port=8080

spring.output.ansi.enabled=ALWAYS

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://ep-snowy-mouse-awycvg31.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require&user=${DB_USER}&password=${DB_PASSWORD}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Debug
debug=true
